import {flagNew} from "./countryStats.js";

let running = [ { country: 'Cyprus', scoreziwEntry: "Νίκος Οικονομόπουλος (CYP) - Βαλ' Το Τέρμα"},
{ country: 'Sweden', scoreziwEntry: 'Husavik (SWE) - My Home Town'},
{ country: 'Croatia', scoreziwEntry: 'Nina Badric (CRO) - Kako si'},
{ country: 'Switzerland', scoreziwEntry: 'Stay With Me (SUI) - Luca Hänni - Topic'},
{ country: 'Austria', scoreziwEntry: 'Melissa Naschenweng (AUT) - Legenden'},
{ country: 'Bulgaria', scoreziwEntry: 'VIKTORIO (BUL) - Tough To Love'},
{ country: 'Finland', scoreziwEntry: 'ABREU (FIN) - Caliente'},
{ country: 'Ukraine', scoreziwEntry: 'Maro (UKR) - HELLSTORM'},
{ country: 'San Marino', scoreziwEntry: 'Madame (SMR) - IL BENE NEL MALE'},
{ country: 'Portugal', scoreziwEntry: 'Sofia Camara (POR) - Who Do I Call Now?'},
{ country: 'Azerbaijan', scoreziwEntry: 'SEVDALIZA (AZE) - ALIBI FT. PABLLO VITTAR & YSEULT'},
{ country: 'Norway', scoreziwEntry: 'Aden Foyer (NOR) - Galileo Galilei'},
{ country: 'Ireland', scoreziwEntry: 'Aimée (IRL) - Daisy Chains'},
{ country: 'Spain', scoreziwEntry: 'Javy Ramírez (ESP) - Tu Nombre'},
{ country: 'Netherlands', scoreziwEntry: 'Hannah Mae & Maksim (NED) - Ik Wil Dat Je Liegt'},
{ country: 'France', scoreziwEntry: 'Niam (FRA) - guignols'},
{ country: 'Israel', scoreziwEntry: 'נרקיס (ISR) - הכל לטובה'},
{ country: 'United Kingdom', scoreziwEntry: 'Tom Walker (UK) - Head Underwater'},
{ country: 'Luxembourg', scoreziwEntry: 'Taska Black (LUX) - Comedown'},
{ country: 'Serbia', scoreziwEntry: 'Marija Serifovic feat. Matija Cvek (SRB) - POLA SUNCA'},
{ country: 'Czechia', scoreziwEntry: 'MIKOLAS (CZE) - DELILAH'},
{ country: 'Monaco', scoreziwEntry: 'Lukas Abdul (MON) - Les Maux Bleus'},
{ country: 'Albania', scoreziwEntry: 'Elhaida Dani (ALB) - Zemrës'},
{ country: 'Germany', scoreziwEntry: 'Gregor Hägele (GER) - 1 Jahr'},
{ country: 'Italy', scoreziwEntry: 'Coma_Cose (ITA) - MALAVITA'},
]



running.forEach((entry, idx) => {
   entry.flag = flagNew(entry.country);
   // console.log(`${idx + 1}.${entry.flag} ${entry.country}`)
   console.log(`${idx + 1}. ${entry.country}`)
})


let countries = [
"Spain",
"Australia",
"Ireland",
"Germany",
"France",
"Switzerland",
"Romania",
"Finland",
"Croatia",
"Estonia",
"Jordan",
"Armenia",
]

countries.forEach((entry, idx) => {
   let flag = flagNew(entry);
   console.log(`${flag} ${entry}`)
})
//    sid: 692246,
//    pass: "4ubK8uhF",
//    flag1: "is",
//    __flag1: "Iceland",
//    name1: "Purple Disco Machine, ÁSDÍS (ISL) - Beat Of Your Heart",
//    sponsor1: "",
//    flag2: "it",
//    __flag2: "Italy",
//    name2: "Cian Ducrot, Matteo Romano (ITA) - Part Of Me",
//    sponsor2: "",
//    flag3: "cz",
//    __flag3: "Czechia",
//    name3: "Aiko (CZE) - Daughter of the Sun",
//    sponsor3: "",
//    flag4: "lu",
//    __flag4: "Luxembourg",
//    name4: "FAST BOY & Topic (LUX) - Forget You",
//    sponsor4: "",
//    flag5: "ch",
//    __flag5: "Switzerland",
//    name5: "Linda Elys (SUI) - House On Fire",
//    sponsor5: "",
//    flag6: "nl",
//    __flag6: "Netherlands",
//    name6: "CMC$ & Asher Angel (NED) - Nobody But You",
//    sponsor6: "",
//    flag7: "fi",
//    __flag7: "Finland",
//    name7: "Jenni Vartiainen (FIN) - Lanka",
//    sponsor7: "",
//    flag8: "es",
//    __flag8: "Spain",
//    name8: "Miriam Rodríguez (ESP) - Debilidad",
//    sponsor8: "",
//    flag9: "dk",
//    __flag9: "Denmark",
//    name9: "Malte Ebert (DEN) - Kalde Dem for Du",
//    sponsor9: "",
//    flag10: "ua",
//    __flag10: "Ukraine",
//    name10: "LOBODA (UKR) - Allo",
//    sponsor10: "",
//    flag11: "mc",
//    __flag11: "Monaco",
//    name11: "TIBZ (MON) - Tout au bout du monde",
//    sponsor11: "",
//    flag12: "sm",
//    __flag12: "San Marino",
//    name12: "Annalisa (SMR) - Euforia",
//    sponsor12: "",
//    flag13: "ie",
//    __flag13: "Ireland",
//    name13: "Dermot Kennedy (IRL) - Kiss Me",
//    sponsor13: "",
//    flag14: "au",
//    __flag14: "Australia",
//    name14: "Troye Sivan (AUS) - Rush",
//    sponsor14: "",
//    flag15: "fr",
//    __flag15: "France",
//    name15: "Adé (FRA) - Tout savoir",
//    sponsor15: "",
//    flag16: "ee",
//    __flag16: "Estonia",
//    name16: "Traffic (EST) - Wunderbar",
//    sponsor16: "",
//    flag17: "no",
//    __flag17: "Norway",
//    name17: "Dagny (NOR) - Somebody",
//    sponsor17: "",
//    flag18: "cy",
//    __flag18: "Cyprus",
//    name18: "Νίκος Οικονομόπουλος (CYP) - Έκπτωτος Άγγελος",
//    sponsor18: "",
//    flag19: "pt",
//    __flag19: "Portugal",
//    name19: "Kura (POR) - Sentir Saudade",
//    sponsor19: "",
//    flag20: "il",
//    __flag20: "Israel",
//    name20: "שי גבסו (ISR) - לא דיברנו כבר שנתיים",
//    sponsor20: "",
//    flag21: "uk",
//    __flag21: "United Kingdom",
//    name21: "Paloma Faith (UK) - Better Than This",
//    sponsor21: "",
//    flag22: "de",
//    __flag22: "Germany",
//    name22: "Gregor Hägele (GER) - Nur Du",
//    sponsor22: "",
//    flag23: "bg",
//    __flag23: "Bulgaria",
//    name23: "HOLY PEAKS (BUL) - Daylight",
//    sponsor23: "",
//    flag24: "be",
//    __flag24: "Belgium",
//    name24: "Berre (BEL) - Thrill Of It All",
//    sponsor24: "",
//    flag25: "se",
//    __flag25: "Sweden",
//    name25: "Loreen (SWE) - Is It Love",
//    sponsor25: "",
//  }
